### ISSUE TITLE
Getting started on the team checklist

### ISSUE THREAD

**Issue by iamciera** [DiscoveryDNA/team_neural_network#22]
## 0. Understand workflow, AWS, and data management

- [ ] Get Slack ID
- All of our code for our work is placed on Github.  Explore the code here [https://github.com/DiscoveryDNA/team_neural_network](https://github.com/DiscoveryDNA/team_neural_network).  Look though to get an idea of how we work.
- [ ] Send Ciera Github ID
- [ ] Read and fully understand our [data_management.md](https://github.com/DiscoveryDNA/team_neural_network/blob/master/data_managment.md) file.  These are many of the rules we use to make sure our work is organized. 
- [ ] Look at the introduction powerpoint: [https://github.com/DiscoveryDNA/welcome/blob/master/week_1_slides.pdf](https://github.com/DiscoveryDNA/welcome/blob/master/week_1_slides.pdf). This is the background of the project. 
- [ ] Our data is based off of the enhancer characterization performed in [Kvon et al, 2014](https://www.nature.com/articles/nature13395).  Read paper as best as possible. Ask questions.
-  [ ] Exercise to get started on AWS.  Make an AWS account with your school email: https://aws.amazon.com/education/awseducate/. They will ask for a credit card, but long as you only use the free instance, you will not be charged.  Start a micro (free) EC2 instance.  Here are some directions: [https://aws.amazon.com/getting-started/tutorials/launch-a-virtual-machine/](https://aws.amazon.com/getting-started/tutorials/launch-a-virtual-machine). Once you have successfully done this, I will get you an account under my account and we can go over the workflow for GPU utilization.  
- [ ] Read [AWS notes](https://github.com/DiscoveryDNA/team_neural_network/blob/master/note/aws_notes.md) in preparation for using GPU machines.
- [ ] With a partner who has already successfully run a gpu machine. Run the [2018-07-11_lstm_naive_trimming_size_1000.ipynb](https://github.com/DiscoveryDNA/team_neural_network/blob/master/code/2018-07-11_lstm_naive_trimming_size_1000.ipynb) notebook.
