### ISSUE TITLE
Understanding the current data and data structures

### ISSUE THREAD

**Issue by iamciera** [DiscoveryDNA/team_neural_network#23]
## 1. Understand the current data and data structures.  

-  Currently the data is all mapped to individual non-coding DNA sequences from 24 species of Drosophila in the Montium Sub Group. 
- These DNA sequences were part of a [previous experiment](http://enhancers.starklab.org/) that tested if these [orthologous](https://en.wikipedia.org/wiki/Sequence_homology#Orthology) sequences were functional or not in Drosophila. The raw sequences can be found [here](https://drive.google.com/drive/folders/19LV8QSPFbsEvglt785RUDKcxHoOiQ5rX) in fasta files. 
		-  The header of the of the fasta files includes this information: 
		Example Fasta header: `VT0847|1|dkik|-|2607`
			- VT0847: Region ID
			- 1: positive presence of expression 
			- dkik: species ID
			- -: read from the negative strand
			- 2607: length of sequence in bp
- Current data Structure:
	- Each letter is one hot encoded. Which means that each nucleotid (ATC or G) is a dictionary and each position is coded along that dictionary. 
	- The positive or negative presence of expression is used as a binary classifier for our current network. 1 = positive expression in early embryo, 0 = negative. 
	- Each nucleotide letter in each position of every sequences can have motif scores attached to it in seperate layers.  Each layer represents a different motif.  The higher the motif score the more likely that that letter begins the first letter of a motif defining a TFBS. This is based on work from the [map_motif](https://github.com/DiscoveryDNA/map_motif) and [TFBS_presence](https://github.com/DiscoveryDNA/TFBS_presence) teams. 

### To-do

- [ ] Read the "Data Processing" section of [basic_neural_network.ipynb](https://github.com/DiscoveryDNA/team_neural_network/blob/master/code/archive/basic_neural_network.ipynb). Make sure you understand the data processing part of this code completely. 
- [ ] Read through the [utility](https://github.com/DiscoveryDNA/team_neural_network/tree/master/code/utility) scripts and make sure you understand what is happening in this code. 
	-  [ ] Understand the pickle library and what it means to create a buffer file.
