### ISSUE TITLE
Hybrid Model To-do May 24

### ISSUE THREAD

**Issue by iamciera** [DiscoveryDNA/team_neural_network#40]
- [ ] Test on Thomas data, see if it can extract known motifs.
- [ ] Data augmentation on D. mel sequences.
- [ ] Check the implementation, Pytorch and keras.  What is causing the differences?
